sonar.projectKey=quality-lab-demo
sonar.projectName=Quality Lab Demo
sonar.sources=backend/src/main/java
sonar.tests=backend/src/test/java
sonar.java.binaries=backend/target/classes
sonar.projectKey=jhonmetal_web-bitwarden
sonar.organization=jhonmetal
sonar.projectName=web_bitwarden
sonar.projectVersion=1.0